language: node_js

node_js: stable

cache:
    apt: true
    directories:
        - node_modules

notifications:
    email:
        recipients:
            - hao.ch86@gmail.com
        on_success: change
        on_failure: always

before_install:
    - export TZ='Pacific/Auckland'
    - npm install hexo-cli -g
    - chmod +x ./publish-to-gh-pages.sh

install:
    - npm install
    - git clone https://github.com/theme-next/hexo-theme-next themes/next

script:
    - hexo clean
    - hexo g

after_script:
    - ./publish-to-gh-pages.sh

branches:
    only:
        - source

env:
    global:
        # Github Pages
        - GH_REF: github.com/hche608/blog.hax3.github.io.git
